openapi: "3.0.3"
info:
  title: "mad_chat_api API"
  description: "mad_chat_api API"
  version: "1.0.0"
servers:
- url: "http://localhost:8080"
paths:
  /messages:
    get:
      description: ""
      parameters:
      - name: "lastMessageId"
        in: "query"
        required: false
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Message"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "error"
  /sendMessage:
    post:
      description: ""
      requestBody:
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/MessageRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "error"
components:
  schemas:
    Message:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        user:
          type: "string"
        content:
          type: "string"
        timestamp:
          type: "integer"
          format: "int64"
      required:
      - "user"
      - "content"
    MessageRequest:
      type: "object"
      properties:
        user:
          type: "string"
        content:
          type: "string"
      required:
      - "user"
      - "content"